# Introduction to numpy, pandas, and matplotlib

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np, pd, plt

(<module 'numpy' from 'C:\\Users\\akoto\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\numpy\\__init__.py'>,
 <module 'pandas' from 'C:\\Users\\akoto\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\pandas\\__init__.py'>,
 <module 'matplotlib.pyplot' from 'C:\\Users\\akoto\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\matplotlib\\pyplot.py'>)

## numpy datatypes

### float32

In [3]:
x = np.float32(2 ** 127)
x, type(x)

(1.7014118e+38, numpy.float32)

### float64

In [4]:
x = np.float64(2) ** 1024
x, type(x)

C:\Users\akoto\AppData\Local\Temp\ipykernel_14972\1333001857.py:1: RuntimeWarning: overflow encountered in scalar power
  x = np.float64(2) ** 1024


(inf, numpy.float64)

In [5]:
lst = [1, 2, 3, 4, 5.]
array = np.array(lst)
array, type(array), array.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [6]:
# np.arange creates an array similar to how one will use for loop // generator
# to create a list
range_array = np.arange(0, 101)
range_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
start = 0
end = 100
interval = 10
range_array = np.arange(start, end + 1, interval)
range_array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
range_list = [i for i in range(start, end + 1, interval)]
range_list

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

## two dimensional lists and arrays

In [9]:
list_of_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
two_dim_array = np.array(list_of_list)
two_dim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
two_dim_array[0]

array([1, 2, 3])

In [12]:
two_dim_array[0][0]

1

In [13]:
two_dim_array[0][1]

2

In [14]:
for i in range(len(two_dim_array)):
    print(i)
    print(two_dim_array[i])

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


In [15]:
print('i j')
for i in range(len(two_dim_array)):
    row = two_dim_array[i]
    for j in range(len(row)):
        print(i, j)
        print('val:', row[j])

i j
0 0
val: 1
0 1
val: 2
0 2
val: 3
1 0
val: 4
1 1
val: 5
1 2
val: 6
2 0
val: 7
2 1
val: 8
2 2
val: 9


### passing the row to a second for loop will cycle through the second (row) 

In [16]:
for row in two_dim_array:
    print(row)
    for val in row:
        print(val)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


### np.zeros(), np.ones(), np.empty()
### np.zeros_like(list/array), np.ones_like(list/array), np.empty_like(list/array)

In [17]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
l = list_of_list
np.zeros_like(l)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones_like(l)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
np.empty_like(l)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### log values

In [23]:
np.log(1)

0.0

In [24]:
np.log(np.e)

1.0

In [25]:
np.log(two_dim_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [26]:
pi = np.pi
e = np.e
lne = np.log(e)
infinity = np.inf
null_val = np.nan
pi, e, lne, infinity, null_val

(3.141592653589793, 2.718281828459045, 1.0, inf, nan)